"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowUpRight, Camera, Clock3, Eye, ImageUp, LayoutDashboard, LogOut, MessageCircle, MousePointerClick, Save, Settings2, Sparkles, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";

type Data={settings:Record<string,string>;therapists:Array<Record<string,any>>;analytics:{totals:Record<string,number>;sources:Array<Record<string,any>>;days:Array<Record<string,any>>;events:Array<Record<string,any>>}};
const priceFields=[
  ["price_calm_30","Quiet Flow · 30 min"],["price_calm_60","Quiet Flow · 60 min"],["price_calm_90","Quiet Flow · 90 min"],
  ["price_deep_60","Deep Release · 60 min"],["price_deep_90","Deep Release · 90 min"],["price_aroma_60","Aroma Ritual · 60 min"],["price_aroma_90","Aroma Ritual · 90 min"],
];
const businessFields=[["registration_fee","Registration fee"],["business_phone","Phone"],["telegram_username","Telegram username"],["opening_hours","Opening hours"],["address","Address"],["meta_pixel_id","Meta Pixel ID"],["adsense_client_id","AdSense client ID"]];

export default function AdminDashboard({email,signOutPath,storageReady}:{email:string;signOutPath:string;storageReady:boolean}){
  const [data,setData]=useState<Data|null>(null);const [settings,setSettings]=useState<Record<string,string>>({});const [therapists,setTherapists]=useState<Array<Record<string,any>>>([]);const [saving,setSaving]=useState(false);
  const load=async()=>{const res=await fetch("/api/admin/data",{cache:"no-store"});if(!res.ok)throw new Error("Could not load dashboard");const json=await res.json();setData(json);setSettings(json.settings);setTherapists(json.therapists.length?json.therapists:[{id:"t1",name_en:"Therapist One",name_hi:"थेरेपिस्ट एक",speciality_en:"Relaxation massage",speciality_hi:"रिलैक्सेशन मसाज",active:1,imageUrl:"/images/therapist-demo-1.png"},{id:"t2",name_en:"Therapist Two",name_hi:"थेरेपिस्ट दो",speciality_en:"Deep-pressure techniques",speciality_hi:"डीप-प्रेशर तकनीक",active:1,imageUrl:"/images/therapist-demo-2.png"}])};
  useEffect(()=>{load().catch((e)=>toast.error(e.message))},[]);
  const events=useMemo(()=>Object.fromEntries((data?.analytics.events??[]).map((x)=>[x.event_name,Number(x.count)])),[data]);
  async function save(){setSaving(true);try{const body={settings,therapists:therapists.map(t=>({id:t.id,nameEn:t.name_en,nameHi:t.name_hi,specialityEn:t.speciality_en,specialityHi:t.speciality_hi,active:Boolean(t.active)}))};const res=await fetch("/api/admin/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!res.ok)throw new Error("Update failed");toast.success("Changes published to site data");await load()}catch(e){toast.error(e instanceof Error?e.message:"Update failed")}finally{setSaving(false)}}
  async function upload(id:string,file?:File){if(!file)return;const form=new FormData();form.append("therapistId",id);form.append("file",file);toast.loading("Uploading portrait…",{id:"upload"});const res=await fetch("/api/admin/upload",{method:"POST",body:form});const json=await res.json();if(!res.ok){toast.error(json.error??"Upload failed",{id:"upload"});return}setTherapists(v=>v.map(t=>t.id===id?{...t,imageUrl:json.imageUrl}:t));toast.success("Portrait updated",{id:"upload"})}
  if(!data)return <main className="admin-loading"><Sparkles/><p>Preparing your spa command centre…</p></main>;
  const totals=data.analytics.totals;return <div className="admin-shell"><Toaster position="top-right"/><aside className="admin-rail"><div className="admin-logo"><Sparkles/></div><nav><a href="#overview" aria-label="Overview"><LayoutDashboard/></a><a href="#content" aria-label="Content"><Settings2/></a><a href="#team" aria-label="Team"><Users/></a></nav><a href={signOutPath} target="_top" aria-label="Sign out"><LogOut/></a></aside><main className="admin-main"><header className="admin-top"><div><span>SPA COMMAND CENTRE</span><h1>Good to see you.</h1><p>{email}</p></div><div><Link href="/" target="_blank">View site <ArrowUpRight/></Link><button onClick={save} disabled={saving}><Save/>{saving?"Saving…":"Save changes"}</button></div></header>
  <Tabs defaultValue="overview" className="admin-tabs"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="content">Prices & ads</TabsTrigger><TabsTrigger value="team">Team media</TabsTrigger></TabsList>
  <TabsContent value="overview" id="overview"><section className="metric-grid"><Metric icon={<Eye/>} label="Unique visitors" value={totals.visitors??0} accent="coral"/><Metric icon={<Activity/>} label="Sessions" value={totals.sessions??0}/><Metric icon={<Clock3/>} label="Avg. time" value={`${Math.round((totals.avg_duration??0)/60)}m`}/><Metric icon={<MousePointerClick/>} label="Telegram clicks" value={events.telegram_click??0} accent="yellow"/></section><section className="admin-analytics-grid"><article className="chart-card wide"><div><span>VISITOR MOMENTUM</span><h2>Last 30 days</h2></div><ResponsiveContainer width="100%" height={260}><AreaChart data={data.analytics.days}><defs><linearGradient id="visitors" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff684d" stopOpacity={.7}/><stop offset="1" stopColor="#ff684d" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#dfe6e2"/><XAxis dataKey="day" hide/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="visitors" stroke="#ff684d" fill="url(#visitors)" strokeWidth={3}/></AreaChart></ResponsiveContainer></article><article className="chart-card"><div><span>ACQUISITION</span><h2>Traffic sources</h2></div><ResponsiveContainer width="100%" height={260}><BarChart data={data.analytics.sources} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="source" width={90} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="sessions" fill="#0b493f" radius={[0,9,9,0]}/></BarChart></ResponsiveContainer></article><article className="event-card"><span>CTA SIGNALS</span><h2>Actions that matter</h2>{[["Call clicks",events.call_click??0],["Telegram",events.telegram_click??0],["Enquiry starts",events.enquiry_start??0],["Enquiry success",events.enquiry_success??0]].map(([label,value])=><div key={String(label)}><b>{value}</b><span>{label}</span></div>)}</article></section></TabsContent>
  <TabsContent value="content" id="content"><section className="admin-editor"><div className="editor-heading"><span>LIVE CONTENT</span><h2>Prices, contact & campaign IDs</h2><p>Updates appear in the public experience without rebuilding the site.</p></div><div className="editor-grid">{priceFields.map(([key,label])=><label key={key}><span>{label}</span><input value={settings[key]??""} onChange={e=>setSettings(v=>({...v,[key]:e.target.value}))} placeholder="₹ —"/></label>)}{businessFields.map(([key,label])=><label className={key==="address"?"wide":""} key={key}><span>{label}</span><input value={settings[key]??""} onChange={e=>setSettings(v=>({...v,[key]:e.target.value}))} placeholder={key.includes("pixel")||key.includes("adsense")?"Disabled until configured":"Enter value"}/></label>)}</div><div className="privacy-note"><Sparkles/><p>Meta Pixel and AdSense load only after a visitor chooses advertising cookies. No enquiry details are sent to advertising platforms.</p></div></section></TabsContent>
  <TabsContent value="team" id="team"><section className="team-editor"><div className="editor-heading"><span>PROFESSIONAL PROFILES</span><h2>Team portraits & expertise</h2><p>Generated portraits are demo-only. Upload real consented staff photos before public launch.</p></div>{therapists.map((t,i)=><article key={t.id}><div className="team-photo"><img src={t.imageUrl??`/images/therapist-demo-${i+1}.png`} alt="Therapist profile"/><label><ImageUp/><span>Replace photo</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(t.id,e.target.files?.[0])} disabled={!storageReady}/></label></div><div className="team-fields"><label><span>English name</span><input value={t.name_en} onChange={e=>setTherapists(v=>v.map(x=>x.id===t.id?{...x,name_en:e.target.value}:x))}/></label><label><span>Hindi name</span><input value={t.name_hi} onChange={e=>setTherapists(v=>v.map(x=>x.id===t.id?{...x,name_hi:e.target.value}:x))}/></label><label><span>English speciality</span><input value={t.speciality_en} onChange={e=>setTherapists(v=>v.map(x=>x.id===t.id?{...x,speciality_en:e.target.value}:x))}/></label><label><span>Hindi speciality</span><input value={t.speciality_hi} onChange={e=>setTherapists(v=>v.map(x=>x.id===t.id?{...x,speciality_hi:e.target.value}:x))}/></label><div className="active-row"><div><b>Visible on site</b><small>Hide without deleting the profile</small></div><Switch checked={Boolean(t.active)} onCheckedChange={checked=>setTherapists(v=>v.map(x=>x.id===t.id?{...x,active:checked?1:0}:x))}/></div></div></article>)}</section></TabsContent></Tabs></main></div>}

function Metric({icon,label,value,accent}:{icon:React.ReactNode;label:string;value:string|number;accent?:string}){return <article className={`metric-card ${accent??""}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>}
