"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Cookie, ShieldCheck, Sparkles, X } from "lucide-react";

type Choice="unset"|"essential"|"analytics"|"ads";
type PublicConfig={settings?:Record<string,string>};

export default function AnalyticsTracker(){
  const [showConsent,setShowConsent]=useState(false);useEffect(()=>{const scroll=()=>setShowConsent(scrollY>window.innerHeight*.65);window.addEventListener("scroll",scroll,{passive:true});return()=>window.removeEventListener("scroll",scroll)},[]);
  const [choice,setChoice]=useState<Choice>("unset");const [config,setConfig]=useState<PublicConfig>({});const started=useRef(Date.now());
  useEffect(()=>{setChoice((localStorage.getItem("spa-cookie-choice") as Choice)||"unset");fetch("/api/public-config").then(r=>r.json()).then(setConfig).catch(()=>undefined);const open=()=>setChoice("unset");window.addEventListener("open-cookie-preferences",open);return()=>window.removeEventListener("open-cookie-preferences",open)},[]);
  const sessionId=useCallback(()=>{let id=sessionStorage.getItem("spa-session-id");if(!id){id=crypto.randomUUID();sessionStorage.setItem("spa-session-id",id)}return id},[]);
  const send=useCallback((eventName:string,extra:Record<string,unknown>={})=>{if(choice!=="analytics"&&choice!=="ads")return;const params=new URLSearchParams(location.search);const payload={consent:true,consentVersion:"2026-10",sessionId:sessionId(),eventName,path:location.pathname,durationSeconds:Math.round((Date.now()-started.current)/1000),utmSource:params.get("utm_source")||undefined,utmMedium:params.get("utm_medium")||undefined,utmCampaign:params.get("utm_campaign")||undefined,referrer:document.referrer||undefined,...extra};fetch("/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),keepalive:true}).catch(()=>undefined)},[choice,sessionId]);
  useEffect(()=>{if(choice!=="analytics"&&choice!=="ads")return;send("page_view");const click=(event:MouseEvent)=>{const el=(event.target as Element).closest<HTMLElement>("[data-track],a[href^='tel:'],a[href*='t.me/']");if(!el)return;const href=el instanceof HTMLAnchorElement?el.href:"";const name=el.dataset.track||(href.startsWith("tel:")?"call_click":href.includes("t.me/")?"telegram_click":"");if(name)send(name,{buttonId:el.dataset.button,serviceId:el.dataset.service})};const custom=(event:Event)=>{const detail=(event as CustomEvent<{name:string;serviceId?:string}>).detail;if(detail?.name)send(detail.name,{...detail})};document.addEventListener("click",click);window.addEventListener("spa-analytics",custom);const timer=setInterval(()=>send("heartbeat"),15000);const hidden=()=>{if(document.visibilityState==="hidden")send("heartbeat")};document.addEventListener("visibilitychange",hidden);return()=>{document.removeEventListener("click",click);window.removeEventListener("spa-analytics",custom);document.removeEventListener("visibilitychange",hidden);clearInterval(timer)}},[choice,send]);
  useEffect(()=>{if(choice!=="ads")return;const meta=config.settings?.meta_pixel_id;const adsense=config.settings?.adsense_client_id;if(meta){const w=window as typeof window&{fbq?:((...args:unknown[])=>void)&{callMethod?:boolean;queue?:unknown[];loaded?:boolean;version?:string}};if(!w.fbq){const fbq=((...args:unknown[])=>{fbq.queue?.push(args)}) as typeof w.fbq;fbq.queue=[];fbq.loaded=true;fbq.version="2.0";w.fbq=fbq;const s=document.createElement("script");s.async=true;s.src="https://connect.facebook.net/en_US/fbevents.js";document.head.appendChild(s)}w.fbq?.("init",meta);w.fbq?.("track","PageView")}if(adsense&&!document.querySelector("script[data-adsense]")){const s=document.createElement("script");s.async=true;s.crossOrigin="anonymous";s.dataset.adsense="true";s.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(adsense)}`;document.head.appendChild(s)}},[choice,config]);
  function choose(value:Choice){localStorage.setItem("spa-cookie-choice",value);setChoice(value)}
  if(choice!=="unset"||!showConsent)return null;
  return <aside className="consent-card" aria-label="Cookie preferences"><button className="consent-close" aria-label="Essential cookies only" onClick={()=>choose("essential")}><X/></button><div className="consent-icon"><Cookie/></div><div><span>YOUR PRIVACY, YOUR CHOICE</span><h2>A calm website should not follow you without asking.</h2><p>Essential features always work. Analytics helps us understand pages and clicks using a daily hashed visitor identifier. Advertising scripts load only if you allow all.</p></div><div className="consent-actions"><button onClick={()=>choose("essential")}>Essential only</button><button onClick={()=>choose("analytics")}>Allow analytics</button><button className="allow-all" onClick={()=>choose("ads")}><Sparkles/> Allow all</button></div><small><ShieldCheck/> No enquiry form details are sent to Meta or Google.</small></aside>
}
