"use client";
import {useEffect,useRef,useState} from "react";
import {Play,Pause,Sparkles} from "lucide-react";
export default function RiveCharacter(){
 const canvas=useRef<HTMLCanvasElement>(null),container=useRef<HTMLDivElement>(null),instance=useRef<any>(null);const [ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[error,setError]=useState(false);
 useEffect(()=>{let disposed=false,resize:ResizeObserver|undefined;const observer=new IntersectionObserver(async entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();try{const {Rive,RuntimeLoader,Layout,Fit,Alignment}=await import("@rive-app/canvas");if(disposed||!canvas.current)return;RuntimeLoader.setWasmUrl("/animations/rive.wasm");const reduced=matchMedia("(prefers-reduced-motion:reduce)").matches;const animation=new Rive({src:"/animations/character-poses.riv",canvas:canvas.current,autoplay:false,layout:new Layout({fit:Fit.Contain,alignment:Alignment.Center}),onLoad:()=>{if(disposed)return;animation.resizeDrawingSurfaceToCanvas();setReady(true);if(!reduced){const name=animation.stateMachineNames[0]||animation.animationNames[0];if(name)animation.play(name);setPlaying(Boolean(name))}},onLoadError:()=>setError(true)});instance.current=animation;resize=new ResizeObserver(()=>animation.resizeDrawingSurfaceToCanvas());resize.observe(canvas.current)}catch{setError(true)}},{rootMargin:"150px"});if(container.current)observer.observe(container.current);return()=>{disposed=true;observer.disconnect();resize?.disconnect();instance.current?.cleanup()}},[]);
 function toggle(){const r=instance.current;if(!r)return;if(playing)r.pause();else r.play(r.stateMachineNames[0]||r.animationNames[0]);setPlaying(!playing)}
 return <div ref={container} className="rive-ritual"><div className="rive-stage" aria-label="Animated character poses"><canvas ref={canvas}/>{!ready&&<span><Sparkles/>{error?"Take a moment for yourself.":"A moment of play…"}</span>}</div><div><span className="kicker">A LITTLE LIGHTNESS</span><h3>Make space for a lighter mood.</h3><p>Slow down. Unwind. Start your next chapter feeling refreshed.</p>{ready&&<button onClick={toggle} aria-label={playing?"Pause character animation":"Play character animation"}>{playing?<Pause/>:<Play/>}{playing?"Pause animation":"Play animation"}</button>}<small>Character poses · Rive community animation</small></div></div>
}
